import "./theme.css";
import "@coinbase/onchainkit/styles.css";
import type { Metadata, Viewport } from "next";
import "./globals.css";
import { Providers } from "./providers";

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
};

export async function generateMetadata(): Promise<Metadata> {
  const URL = process.env.NEXT_PUBLIC_URL;
  const PROJECT_NAME = process.env.NEXT_PUBLIC_ONCHAINKIT_PROJECT_NAME;
  const HERO_IMAGE = process.env.NEXT_PUBLIC_APP_HERO_IMAGE;
  const SPLASH_IMAGE = process.env.NEXT_PUBLIC_SPLASH_IMAGE;
  const SPLASH_BG = process.env.NEXT_PUBLIC_SPLASH_BACKGROUND_COLOR;

  const manifest = {
    version: "next",
    imageUrl: HERO_IMAGE,
    button: {
      title: `🚀 Launch ${PROJECT_NAME}`,
      action: {
        type: "launch_miniapp", // 👈 using miniapp type
        name: PROJECT_NAME,
        url: URL,
        splashImageUrl: SPLASH_IMAGE,
        splashBackgroundColor: SPLASH_BG,
      },
    },
  };

  const manifestJSON = JSON.stringify(manifest);

  return {
    title: PROJECT_NAME,
    description:
      "Generated by `create-onchain --mini`, a Next.js template for MiniKit",
    icons: {
      icon: "/favicon.ico",
    },
    other: {
      "fc:frame": manifestJSON,
      "fc:miniapp": manifestJSON, // ✅ will now be included in <head>
    },
  };
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-background">
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
