import "./theme.css";
import "@coinbase/onchainkit/styles.css";
import type { Metadata, Viewport } from "next";
import "./globals.css";
import { Providers } from "./providers";
import { WagmiProviderWrapper } from './components/WagmiProvider'

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
};

export async function generateMetadata(): Promise<Metadata> {
  const URL = process.env.NEXT_PUBLIC_URL;
  const PROJECT_NAME = process.env.NEXT_PUBLIC_ONCHAINKIT_PROJECT_NAME;
  const HERO_IMAGE = process.env.NEXT_PUBLIC_APP_HERO_IMAGE;
  const SPLASH_IMAGE = process.env.NEXT_PUBLIC_SPLASH_IMAGE;
  const SPLASH_BG = process.env.NEXT_PUBLIC_SPLASH_BACKGROUND_COLOR;

  const manifest = {
    version: "next",
    imageUrl: "https://basebuilder.vercel.app/logo.png",
   button: {
    title: "🚀 Launch BaseBuilder",
    action: {
      type: "launch_miniapp",
      name: "BaseBuilder",
      url: "https://basebuilder.vercel.app",
      splashBackgroundColor: "#000000",
    },
    },
  };

  const manifestJSON = JSON.stringify(manifest);

  return {
    title: PROJECT_NAME,
    description:
      "Generated by `create-onchain --mini`, a Next.js template for MiniKit",
    icons: {
      icon: "/favicon.ico",
    },
    other: {
      "fc:frame": manifestJSON,
      "fc:miniapp": manifestJSON,
    },
  };
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-background">
        <WagmiProviderWrapper>
        <Providers>{children}</Providers>
        </WagmiProviderWrapper>
      </body>
    </html>
  );
}
